/*
 * build-occt.js — writes lib/occt-import-js.wasm.js: the STEP reader's WebAssembly (lib/occt-import-js.wasm) as
 * base64 text in a script. Opened as a file (file://), the browser won't fetch the .wasm, so Flow › 3D's STEP
 * import loads this like its other scripts and hands the binary to the reader. Run it after updating occt-import-js:
 *   node build-occt.js           write lib/occt-import-js.wasm.js
 *   node build-occt.js --check   fail when it is not the current .wasm
 */
const fs = require('fs'), path = require('path');
const WASM = path.join(__dirname, 'lib', 'occt-import-js.wasm'), OUT = path.join(__dirname, 'lib', 'occt-import-js.wasm.js');

const out = `/* occt-import-js.wasm.js - GENERATED by build-occt.js from occt-import-js.wasm (unmodified, base64); do not edit.
 * For the app opened as a file (file://), where the browser won't fetch the .wasm (Flow > 3D, STEP import). */
self.OCCT_WASM = "${fs.readFileSync(WASM).toString('base64')}";
`;
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== out) { console.error('lib/occt-import-js.wasm.js is out of date: run node build-occt.js'); process.exit(1); }
  console.log('lib/occt-import-js.wasm.js is up to date');
} else {
  fs.writeFileSync(OUT, out);
  console.log(`wrote lib/occt-import-js.wasm.js (${(out.length / 1048576).toFixed(1)} MB)`);
}
