/*
 * build-workers.js — writes workers-src.js: the solvers' worker scripts (cfd-worker.js, cfd-1d-worker.js,
 * cfd-3d-worker.js) and the scripts they import, as text. Opened as a file (file://), the browser refuses a
 * worker from a file and a worker can't load a file either; makeWorker() (cfd-ui.js) then builds each worker
 * in memory from this text. Run it after changing any of those scripts:
 *   node build-workers.js           write workers-src.js
 *   node build-workers.js --check   fail when workers-src.js is not what the scripts give now
 * Each worker's scripts, joined in their import order, are checked to compile and run as one script.
 */
const fs = require('fs'), path = require('path'), vm = require('vm');
const DIR = __dirname, OUT = path.join(DIR, 'workers-src.js');
const WORKERS = ['cfd-worker.js', 'cfd-1d-worker.js', 'cfd-3d-worker.js'];

const read = f => fs.readFileSync(path.join(DIR, f), 'utf8');
/** The scripts a worker imports, in order (its importScripts call). */
function importsOf(f) {
  const m = read(f).match(/importScripts\(([^)]*)\)/);
  if (!m) throw new Error(`${f}: no importScripts`);
  return [...m[1].matchAll(/'([^']+)'/g)].map(x => x[1]);
}
/** A worker as one script: its imports, then itself (makeWorker() in cfd-ui.js joins them the same way). */
const joined = (w, imports, text) => 'self.importScripts = function () {};\n' + [...imports[w], w].map(f => text[f]).join('\n;\n');

function build() {
  const imports = {}, text = {};
  for (const w of WORKERS) {
    imports[w] = importsOf(w);
    for (const f of [...imports[w], w]) text[f] = read(f);
  }
  // each worker's scripts, joined, compile and run (no two declare the same name)
  for (const w of WORKERS) {
    const ctx = vm.createContext({ console, postMessage() {} });
    ctx.self = ctx;
    try { vm.runInContext(joined(w, imports, text), ctx, { filename: w + ' (joined)' }); }
    catch (e) { throw new Error(`${w}: its scripts joined do not run as one script: ${e.message}`); }
    if (typeof ctx.onmessage !== 'function') throw new Error(`${w}: joined, it sets no onmessage`);
  }
  const esc = s => JSON.stringify(s).replace(/[\u007f-\uffff]/g, c => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
  return `/* workers-src.js - GENERATED by build-workers.js from the scripts named below; do not edit (node build-workers.js).
 * The solvers' worker scripts as text: opened as a file (file://), the browser refuses a worker from a file and a
 * worker can't load one, so makeWorker() (cfd-ui.js) builds each worker in memory from this. */
const WORKER_SRC = {
  imports: ${JSON.stringify(imports)},
  text: {
${Object.entries(text).map(([f, t]) => `    ${JSON.stringify(f)}: ${esc(t)}`).join(',\n')}
  },
};
`;
}

const out = build();
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (cur !== out) { console.error('workers-src.js is out of date: run node build-workers.js'); process.exit(1); }
  console.log('workers-src.js is up to date');
} else {
  fs.writeFileSync(OUT, out);
  console.log(`wrote workers-src.js (${(out.length / 1024).toFixed(0)} KB): ${WORKERS.join(', ')}`);
}
